# TCL File Generated by Component Editor 20.1
# Wed Feb 11 20:25:32 EST 2026
# DO NOT MODIFY


# 
# burst_master_4 "burst_master_4" v1.0
#  2026.02.11.20:25:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module burst_master_4
# 
set_module_property DESCRIPTION ""
set_module_property NAME burst_master_4
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME burst_master_4
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL burst_master_4
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file burst_master_4.v VERILOG PATH ../RTL/burst_master_4.v TOP_LEVEL_FILE
add_fileset_file simple_fifo.v VERILOG PATH ../RTL/simple_fifo.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter BURST_COUNT INTEGER 256
set_parameter_property BURST_COUNT DEFAULT_VALUE 256
set_parameter_property BURST_COUNT DISPLAY_NAME BURST_COUNT
set_parameter_property BURST_COUNT TYPE INTEGER
set_parameter_property BURST_COUNT UNITS None
set_parameter_property BURST_COUNT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_COUNT HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 512
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 512
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter PIPE_LATENCY INTEGER 4
set_parameter_property PIPE_LATENCY DEFAULT_VALUE 4
set_parameter_property PIPE_LATENCY DISPLAY_NAME PIPE_LATENCY
set_parameter_property PIPE_LATENCY TYPE INTEGER
set_parameter_property PIPE_LATENCY UNITS None
set_parameter_property PIPE_LATENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIPE_LATENCY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point read_master
# 
add_interface read_master avalon start
set_interface_property read_master addressUnits SYMBOLS
set_interface_property read_master associatedClock clock
set_interface_property read_master associatedReset reset
set_interface_property read_master bitsPerSymbol 8
set_interface_property read_master burstOnBurstBoundariesOnly false
set_interface_property read_master burstcountUnits WORDS
set_interface_property read_master doStreamReads false
set_interface_property read_master doStreamWrites false
set_interface_property read_master holdTime 0
set_interface_property read_master linewrapBursts false
set_interface_property read_master maximumPendingReadTransactions 1
set_interface_property read_master maximumPendingWriteTransactions 0
set_interface_property read_master readLatency 0
set_interface_property read_master readWaitTime 1
set_interface_property read_master setupTime 0
set_interface_property read_master timingUnits Cycles
set_interface_property read_master writeWaitTime 0
set_interface_property read_master ENABLED true
set_interface_property read_master EXPORT_OF ""
set_interface_property read_master PORT_NAME_MAP ""
set_interface_property read_master CMSIS_SVD_VARIABLES ""
set_interface_property read_master SVD_ADDRESS_GROUP ""

add_interface_port read_master rm_address address Output 32
add_interface_port read_master rm_read read Output 1
add_interface_port read_master rm_readdata readdata Input 32
add_interface_port read_master rm_readdatavalid readdatavalid Input 1
add_interface_port read_master rm_waitrequest waitrequest Input 1
add_interface_port read_master rm_burstcount burstcount Output 9


# 
# connection point write_master
# 
add_interface write_master avalon start
set_interface_property write_master addressUnits SYMBOLS
set_interface_property write_master associatedClock clock
set_interface_property write_master associatedReset reset
set_interface_property write_master bitsPerSymbol 8
set_interface_property write_master burstOnBurstBoundariesOnly false
set_interface_property write_master burstcountUnits WORDS
set_interface_property write_master doStreamReads false
set_interface_property write_master doStreamWrites false
set_interface_property write_master holdTime 0
set_interface_property write_master linewrapBursts false
set_interface_property write_master maximumPendingReadTransactions 0
set_interface_property write_master maximumPendingWriteTransactions 0
set_interface_property write_master readLatency 0
set_interface_property write_master readWaitTime 1
set_interface_property write_master setupTime 0
set_interface_property write_master timingUnits Cycles
set_interface_property write_master writeWaitTime 0
set_interface_property write_master ENABLED true
set_interface_property write_master EXPORT_OF ""
set_interface_property write_master PORT_NAME_MAP ""
set_interface_property write_master CMSIS_SVD_VARIABLES ""
set_interface_property write_master SVD_ADDRESS_GROUP ""

add_interface_port write_master wm_write write Output 1
add_interface_port write_master wm_waitrequest waitrequest Input 1
add_interface_port write_master wm_writedata writedata Output 32
add_interface_port write_master wm_burstcount burstcount Output 9
add_interface_port write_master wm_address address Output 32


# 
# connection point cs_slave
# 
add_interface cs_slave avalon end
set_interface_property cs_slave addressUnits WORDS
set_interface_property cs_slave associatedClock clock
set_interface_property cs_slave associatedReset reset
set_interface_property cs_slave bitsPerSymbol 8
set_interface_property cs_slave burstOnBurstBoundariesOnly false
set_interface_property cs_slave burstcountUnits WORDS
set_interface_property cs_slave explicitAddressSpan 0
set_interface_property cs_slave holdTime 0
set_interface_property cs_slave linewrapBursts false
set_interface_property cs_slave maximumPendingReadTransactions 0
set_interface_property cs_slave maximumPendingWriteTransactions 0
set_interface_property cs_slave readLatency 0
set_interface_property cs_slave readWaitTime 1
set_interface_property cs_slave setupTime 0
set_interface_property cs_slave timingUnits Cycles
set_interface_property cs_slave writeWaitTime 0
set_interface_property cs_slave ENABLED true
set_interface_property cs_slave EXPORT_OF ""
set_interface_property cs_slave PORT_NAME_MAP ""
set_interface_property cs_slave CMSIS_SVD_VARIABLES ""
set_interface_property cs_slave SVD_ADDRESS_GROUP ""

add_interface_port cs_slave avs_write write Input 1
add_interface_port cs_slave avs_read read Input 1
add_interface_port cs_slave avs_address address Input 3
add_interface_port cs_slave avs_writedata writedata Input 32
add_interface_port cs_slave avs_readdata readdata Output 32
set_interface_assignment cs_slave embeddedsw.configuration.isFlash 0
set_interface_assignment cs_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cs_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cs_slave embeddedsw.configuration.isPrintableDevice 0

